### PR TITLE
Profilepage

### PR DESCRIPTION
**Pull request by spline2hg**
I have added the profile page using a Profile model and corersponding form, currently this has 2 different  profile page,that we can access

```python
 path('profile/', auth_views.profile, name='profile'),
 path('profile_a/', auth_views.profile_alpine, name='profile')
```
The one available at profile/ uses a is_editing variable to switch between edit and view mode for profile and the one at profile_a uses alpine js for this, there is also diff html files for this, i have tried to fix the issues i faced ,and it seems it works fine other than the few ui changes required, Plz review the PR and let me know there are any changes needed or areas of improvement ,feedback is greatly appreciated, thanks for guiding and letting me work on this

### CODE REVIEW

**Comment by nfoert** [comment]
Thanks for working on this @spline2hg! This looks great
A few things I've noticed:
- Can the profile picture be automatically downscaled to a certain size limit/maximum image size?
- This should eventually be moved to just be one single page, would you like assistance converting it all to use Alpine.js?

Additionally I worked to adjust most of the styles to fit the current theme of the site, I also opened #89, issue #84 will likely adjust how the styles are done anyway

Additionally there's a lot of open issues and discussion around the profile and authentication system (#32, #46, #81, #42), some features (eg. changing password) might need to wait until these are implemented, but perhaps this could still be merged into `development` or a separate branch for managing the new profile and authentication system (to allow you to make sure you still get your hacktoberfest credit in time)

**Comment by spline2hg** [comment]
> Thanks for working on this @spline2hg! This looks great A few things I've noticed:
> 
Yep, Thanks
>     * Can the profile picture be automatically downscaled to a certain size limit/maximum image size?
> 
So something like compression?
>     * This should eventually be moved to just be one single page, would you like assistance converting it all to use Alpine.js?
> 
> 
i have made the alpine js version too, u could access it a profile_a, or did u mean anything, i didnt get it
> Additionally I worked to adjust most of the styles to fit the current theme of the site, I also opened #89, issue #84 will likely adjust how the styles are done anyway
> 
will check it out , thanks, btw how should i now get this changes into my device, a git pull will work right?
> Additionally there's a lot of open issues and discussion around the profile and authentication system (#32, #46, #81, #42), some features (eg. changing password) might need to wait until these are implemented, but perhaps this could still be merged into `development` or a separate branch for managing the new profile and authentication system (to allow you to make sure you still get your hacktoberfest credit in time)
>
ok man no worries, i have time to complete this work, working on this is more fun tbh


And what about this rufff check fail?

**Comment by nfoert** [comment]
> So something like compression?

Yes, ideally this would help with storage size costs as well, for example a user could upload a really detailed logo that takes up a lot of space, enough users doing this and the cost of storage in production will increase
It doesn't necessarily need to compress the file, but not allowing uploads over 2MB or something could be a good implementation

> i have made the alpine js version too, u could access it a profile_a, or did u mean anything, i didnt get it

I think it would be better to move the profile page to just be at `/profile` instead of having `/profile` and `/profile_a`, this will be easier to maintain, and there's some aspects of the two templates that are duplicated, I was under the impression that `/profile_a` was a more experimental example of alpine.js, unless I'm not understanding your plans correctly?

> will check it out , thanks, btw how should i now get this changes into my device, a git pull will work right?

Yes, I've committed the changes to your fork of the code so running `git pull` will get the new changes from your fork

> And what about this rufff check fail?

It seems like it was [flagging a double import](https://github.com/nfoert/cardie/pull/88/checks?sha=e508edd30e315447887bd5895b2ae1b99fe2bfa1), which I see you've just committed to fix so it should be all good now!

**Comment by spline2hg** [comment]
> I think it would be better to move the profile page to just be at `/profile` instead of having `/profile` and `/profile_a`, this will be easier to maintain, and there's some aspects of the two templates that are duplicated, I was under the impression that `/profile_a` was a more experimental example of alpine.js, unless I'm not understanding your plans correctly?
> 
so yeah i will remove the profile_a and keep only the profile/ that will use alpine js for switching part, does this seem right?

>

**Comment by nfoert** [comment]
> so yeah i will remove the profile_a and keep only the profile/ that will use alpine js for switching part, does this seem right?

That sounds good to me @spline2hg! Thanks for working on this

**Comment by spline2hg** [comment]
@nfoert look into the changes and tell any changes if required,.thanks

**Comment by nfoert** [comment]
Thanks for the updated changes! I like how it's looking so far
I thought of a few other additions that could be made:

- Perhaps the profile picture for the user could be shown on the home and index pages on this button? Additionally a button is needed to get to the profile page in the first place, this button could be added here too?
image
- It appears that the profile picture is always saved as the name of the uploaded file, this will cause issues if multiple users upload an image called `profile.png` for example, the files will get overlapped. Perhaps the file name could be changed to a unique ID for each image?

Once this PR is done I'm planning on merging it into a separate branch for all of the profile, authentication, and email changes before all of those features have been implemented. Thanks for your work on this!

**Comment by nfoert** [comment]
> Would you prefer a single dropdown menu with text options for both profile and logout, without including a profile image? 

The best idea I can think of for this would be to modify the existing dropdown to log out and add the button to access the profile and the profile picture there, so we can reuse that element across multiple pages if need be.
Perhaps something like this could work?
image

> i tried this django, its adding a random pattern sequence if the file name already exists, is this fine or should i make changes to give some unique name

Ah okay that's good to know, I guess I didn't test it correctly, that's my mistake. Leaving this behavior as it is now is fine with me!

**Comment by spline2hg** [comment]
i have added a dropdown at home page for profile page and on profile page to home ,does this seem fine, and? and on the home page the dropdown now disappears if clicked anywhere on the page.

i havent done for the starting page what to do for it, as it currently doesnt have a dropdown, what to d about it?

**Comment by nfoert** [comment]
> i have added a dropdown at home page for profile page and on profile page to home ,does this seem fine, and? and on the home page the dropdown now disappears if clicked anywhere on the page.

This looks great! Thanks for implementing this

> i havent done for the starting page what to do for it, as it currently doesnt have a dropdown, what to d about it?

I think it's fine if this page doesn't have a dropdown menu, the button helps give the user a fast way to get to the home page

This feature should be ready to merge! Is there anything else you'd like to implement? Otherwise you can go ahead and convert this PR to no longer be a draft and I'll get it merged for you

**Comment by spline2hg** [comment]
> I think it's fine if this page doesn't have a dropdown menu, the button helps give the user a fast way to get to the home page
> 
That makes sense 
> This feature should be ready to merge! Is there anything else you'd like to implement? Otherwise you can go ahead and convert this PR to no longer be a draft and I'll get it merged for you
>
i was thinking of implementing restricting the image size, for that i was using some validators and raising validation errors when uploading larger than threshold value, but the the image was getting changes nonetheless and it was not showing up on the page.

what i think is i might work on this afterwards in a diff pr , is this fine?apart from this ig most if the things are done , and going forward i will try to do the email authentication,password change and making setting features work.

I will proceed to create a PR from my draft if you don’t have any further suggestions. Thank you so much for all your guidance—I really appreciate it! I look forward to making more contributions to the project.

**Comment by nfoert** [comment]
> i was thinking of implementing restricting the image size, for that i was using some validators and raising validation errors when uploading larger than threshold value

This is a good idea, I think that would be a good thing to implement

> what i think is i might work on this afterwards in a diff pr , is this fine

That sounds good to me

> i will try to do the email authentication,password change and making setting features work.

Okay sounds good, thanks for working on adding all of these features!

I don't have any more suggestions, this feature is working great! Feel free to convert this PR when you're ready or I can do it as well, you should be able to press a button like `Ready for review` to convert it to a normal PR

**Comment by spline2hg** [comment]
@nfoert  changed the PR to a normal PR. I learned a lot of things working on this project,thank youman. Plz let me know if u have any suggestions for me .

Thank You for the help and collaboration!

**Comment by nfoert** [comment]
Thanks for finishing up this PR @spline2hg! It looks great to me, I appreciate the work you've done on this, I'm glad we got to collaborate on this together.
I'll get it all merged now!

**Pull request merged**
