### PR TITLE
chore: add `ruff` to automate and unify formating and linting

### PR DESCRIPTION
**Pull request by ar4s**
I add ruff to check and linting the code. Additonally I have setup one basic step for [Gihub Actions](https://github.com/features/actions) but I not sure if this work at all.

### CODE REVIEW

**Comment by nfoert** [comment]
This is a good idea!
It would be nice if we could also format and lint the HTML, CSS and JavaScript files however, do you know of an option for this?
Additionally it would be good to ensure that the GitHub action is running properly, perhaps we could commit a poorly formatted file and see if it's working?

**Comment by ar4s** [comment]
> It would be nice if we could also format and lint the HTML, CSS and JavaScript files however, do you know of an option for this?
For JavaScript the industry standard is [`eslint`](https://eslint.org/) with plugins, but recently I have discovered [`biome`](https://biomejs.dev/) which is opinionated tool for the web development. Biome has one big advantage to use in `cardie`, you can install it without touching `npm` and other bloated stuff.
For HTML (Django templates) I use [djlint](https://www.djlint.com/) - nice linter and formatter.

> Additionally it would be good to ensure that the GitHub action is running properly, perhaps we could commit a poorly formatted file and see if it's working?
It seems to me that this will become apparent as we merge the changes from `development` to `main`. Then you should see a little green (or red) indicator next to the last commit:

obraz

**Comment by nfoert** [comment]
> For JavaScript the industry standard is [eslint](https://eslint.org/) with plugins, but recently I have discovered [biome](https://biomejs.dev/) which is opinionated tool for the web development. Biome has one big advantage to use in cardie, you can install it without touching npm and other bloated stuff.

Those are good options, I would like to be able to avoid `npm` at this time, I attempted to get JavaScript packages to work in django previously and ran into issues, so `biome` looks like an excellent choice.

> For HTML (Django templates) I use [djlint](https://www.djlint.com/) - nice linter and formatter.

Thanks for this option, this will also be something to look into for later, I created issue #73 for tracking these features

> It seems to me that this will become apparent as we merge the changes from development to main. Then you should see a little green (or red) indicator next to the last commit:

That makes sense, I'll go ahead and get this merged now and we can see if it worked. Thanks again for implementing this!

Also my apologies for the slow responses - I've had a busy week

**Comment by nfoert** [comment]
@ar4s this is interesting, the [workflow run](https://github.com/nfoert/cardie/actions/runs/11187560875/job/31104856393) seems to have errored out when it found a linting warning
image
Based on the response from the workflow run, it appears that we can add the `--fix` argument to the `ruff.yaml` file to lint it automatically, I do think this could cause issues though, in case the code gets modified on push and then something breaks

**Comment by ar4s** [comment]
> Based on the response from the workflow run, it appears that we can add the --fix argument to the ruff.yaml file to lint it automatically, I do think this could cause issues though, in case the code gets modified on push and then something breaks

That is fine I mean it is expected behaviour. On CI we only want to check code through checkers and linters, it is a developer's duty to run this on their local machine and fix it. Of course it is possible to run `--fix` automatically on CI, but there is the challenge of committing changes to the repository after the command has been run - you need some kind of user in terms of git to do that.

**Comment by ar4s** [comment]
@nfoert I fix that in https://github.com/nfoert/cardie/pull/75
Now each PR has additional section with checks:
obraz

**Pull request merged**
