### PR TITLE
Update footer.css

### PR DESCRIPTION
**Pull request by sarthakjalan05**
fixed issue #22 
please check and tell me if you need more refinements.
@nfoert

### CODE REVIEW

**Comment by nfoert** [comment]
Hi, thanks for working on this! It appears that this is working as intended on the index page but the positioning of the footer has some issues on other pages when using the mobile view inspector

I don't know exactly why this is, I've had troubles with getting the footer positioning to work correctly in the past

Screen Shot 2024-10-06 at 19 43 24
`/home` and `/authentication`

**Comment by sarthakjalan05** [comment]
> Hi, thanks for working on this! It appears that this is working as intended on the index page but the positioning of the footer has some issues on other pages when using the mobile view inspector
> 
> I don't know exactly why this is, I've had troubles with getting the footer positioning to work correctly in the past
> 
> Screen Shot 2024-10-06 at 19 43 24 `/home` and `/authentication`

sure I am working on that @nfoert

**Comment by sarthakjalan05** [comment]
Hi @nfoert please check I have fixed both the pages. Let me know if you need some other changes :). And if not please merge these under the hacktoberfest tag.

**Comment by nfoert** [comment]
@sarthakjalan05, this does work as intended now! However, the point of the `footer.css` file was to allow an organized way to add the necessary footer styles to every page, is is possible to put all of the new CSS rules just in `footer.css` instead of `home.css` and `authentication.css`?

**Comment by sarthakjalan05** [comment]
@nfoert I tried to do what you asked but I couldn't find a way to do that.

**Comment by nfoert** [comment]
> I tried to do what you asked but I couldn't find a way to do that.

No worries @sarthakjalan05, thanks for working on this! I made a small change, `position: sticky` had some strange behaviors on smaller screens, and there was some unused styles, otherwise this has been finished, I'll get it merged now!

**Pull request merged**
