### PR TITLE
Closes #53: Update from cursor to pointer on the Homepage

### LINKED ISSUE #53: Enhance UX: Change cursor to pointer on hover for buttons
### Description:
The hover effect for the buttons on the homepage (`Try Cardie`, `Source Code`, and `Sign In`) does not currently show a pointer cursor. This can be improved by changing the cursor style to `pointer` when hovering over these interactive elements.

### Steps to Reproduce:
1. Go to the homepage.
2. Hover over the buttons (`Try Cardie`, `Source Code`, `Sign In`).
3. Notice that the cursor remains as the default cursor, indicating no interactive action.

###ScreenShot:
Screenshot from 2024-10-02 01-00-10

### Expected Behavior:
The cursor should change to a pointer when hovering over these buttons to indicate interactivity.

### Suggested Solution:
In the CSS, add the following rule for the buttons:

### PR DESCRIPTION
**Pull request by Vineet8800**
Close #53 : 

### Code changes:

1. Create a common CSS class called `ui_cursor_pointer`
2. Use `ui_cursor_pointer` with buttons on the Homepage

### CODE REVIEW

**Comment by nfoert** [comment]
As per my comment from #53, someone else has been assigned to this already so I will save your PR for later in case they decide to not work on this issue anymore.

Additionally, why not just add `cursor: pointer` to the different UI button elements instead of a separate class? This would be much easier to maintain. 
Nevertheless, I will not be merging this PR unless the original assignee of the issue decides they no longer wish to work on it, I'm just trying to be fair to who wants to work on what :)

**Comment by Vineet8800** [comment]
So the purpose of creating a separate CSS class is not to modify existing buttons in other parts of the code. If I had added `cursor: pointer` to the existing class, it would have changed everywhere. If this is needed, then I can update the code. Please let me know.
I have replied on #53 for you.

**Comment by nfoert** [comment]
> If I had added cursor: pointer to the existing class, it would have changed everywhere.

It would make more sense for this to be changed everywhere, as it would be inconsistent to only change the pointer to the buttons on the index page. This should be done to all of the button classes so it can be a consistent change across the project, and this will be easier to maintain.

This issue has now been assigned to you as the person before decided not to work on it anymore 👍🏼

**Comment by nfoert** [comment]
Thanks for working on this @Vineet8800! I made a small change (one of the buttons didn't get the new CSS) but otherwise it looks good to me!

**Pull request merged**
